---
language: python
jobs:
  include:
    - name: "Python 3.9 on Linux"
      python: '3.9'
    - name: "Python 3.? on OSX"
      os: osx
      osx_image: xcode12.2
      language: shell

branches: main

os:
  - linux
  - osx

dist: focal

install:
  - pip3 install --upgrade pip ansible
  - ansible --version
  - python3 --version
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
