---
language: python
python: '3.9'

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

env:
- OS=alpine_3.11
- OS=alpine_3.12
- OS=alpine_edge
- OS=archlinux_latest
- OS=centos_7
- OS=centos_8
- OS=debian_buster
- OS=debian_stretch
- OS=fedora_31
- OS=fedora_32
- OS=ubi8_8.1
- OS=ubi8_8.2
- OS=ubuntu_bionic
- OS=ubuntu_focal
- OS=ubuntu_xenial
