---
language: python
python: '3.9'

branches: main

os:
  - linux
  - osx

dist: focal

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
